version: 2.1

orbs:
  python: circleci/python@1.3.4

jobs:
  graph-api-build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          app-dir: ./graph_api
          pkg-manager: pip
      - run:
          command: python ./manage.py test graph_api
          name: Test
  grisera-api-build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          app-dir: ./grisera_api
          pkg-manager: pip
      - run:
          command: python ./manage.py test grisera_api
          name: Test

workflows:
  main:
    jobs:
      - graph-api-build-and-test
      - grisera-api-build-and-test