version: 2.1

orbs:
  python: circleci/python@1.3.4

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ .Branch }}
      - python/install-packages:
          app-dir: ./graph_api
          pkg-manager: pip
      - python/install-packages:
          app-dir: ./grisera_api
          pkg-manager: pip
      - save_cache:
          key: cache-{{ .Branch }}
          paths: 
            - .
      - run:
          command: ./manage.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test