version: 2.1

orbs:
  python: circleci/python@1.3.4

jobs:
  graph-api-build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          app-dir: ./graph_api
          pkg-manager: pip
      - run:
          command: python ./graph_api/manage.py test
          name: Test
  grisera-api-build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          app-dir: ./grisera_api
          pkg-manager: pip
      - run:
          command: python ./grisera_api/manage.py test
          name: Test
  ontology-api-build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          app-dir: ./ontology_api
          pkg-manager: pip
      - run:
          command: |
            mkdir tests/tmp_owl
            python ./ontology_api/manage.py test
          name: Test

workflows:
  main:
    jobs:
      - graph-api-build-and-test
      - grisera-api-build-and-test
      - ontology-api-build-and-test
